/**************************************************************************************************
	Test dev: 123456789


Création le: 20/01/2020 à 10:32
Auteur: OJE

Version PeTRA:1.3.5
****************************************************************************************************/

DELETE FROM SOC1.PARAV WHERE codsoc=~societe and codfct='STRPV';
INSERT INTO SOC1.PARAV(CODSOC, DATMOD, UTIMOD, CODPAR, CODFCT, LIBPAR, PARA1, PARA2, PARA3, PARM1, PARM2, PARN1, PARN2, PARN3, PARN4, PARN5, PARD1, PARD2, PARD3, ACTIF) VALUES(~societe, to_char(SYSDATE,'YYYYMMDD'), 'OSI_SQL', 'CODCTG', 'STRPV', ' ', 'A8', ' ', ' ', ' ', ' ', 0, 0, 0, 0, 0, 0, 0, 0, 'N');
INSERT INTO SOC1.PARAV(CODSOC, DATMOD, UTIMOD, CODPAR, CODFCT, LIBPAR, PARA1, PARA2, PARA3, PARM1, PARM2, PARN1, PARN2, PARN3, PARN4, PARN5, PARD1, PARD2, PARD3, ACTIF) VALUES(~societe, to_char(SYSDATE,'YYYYMMDD'), 'OSI_SQL', 'DUPENT', 'STRPV', null, 'ETRP', 'TRF', ' ', null, null, 1, 0, 0, 0, 0, 0, 0, 0, 'O');
INSERT INTO SOC1.PARAV(CODSOC, DATMOD, UTIMOD, CODPAR, CODFCT, LIBPAR, PARA1, PARA2, PARA3, PARM1, PARM2, PARN1, PARN2, PARN3, PARN4, PARN5, PARD1, PARD2, PARD3, ACTIF) VALUES(~societe, to_char(SYSDATE,'YYYYMMDD'), 'OSI_SQL', 'CODCPT', 'STRPV', 'TRPTRROTR', 'TRAN', ' ', ' ', ' ', ' ', 0, 0, 0, 0, 0, 0, 0, 0, 'O');
INSERT INTO SOC1.PARAV(CODSOC, DATMOD, UTIMOD, CODPAR, CODFCT, LIBPAR, PARA1, PARA2, PARA3, PARM1, PARM2, PARN1, PARN2, PARN3, PARN4, PARN5, PARD1, PARD2, PARD3, ACTIF) VALUES(~societe, to_char(SYSDATE,'YYYYMMDD'), 'OSI_SQL', 'PRXPMP', 'STRPV', ' ', ' ', ' ', ' ', ' ', ' ', 0, 0, 0, 0, 0, 0, 0, 0, 'O');
INSERT INTO SOC1.PARAV(CODSOC, DATMOD, UTIMOD, CODPAR, CODFCT, LIBPAR, PARA1, PARA2, PARA3, PARM1, PARM2, PARN1, PARN2, PARN3, PARN4, PARN5, PARD1, PARD2, PARD3, ACTIF) VALUES(~societe, to_char(SYSDATE,'YYYYMMDD'), 'OSI_SQL', 'LOGGEN', 'STRPV', ' ', ' ', ' ', ' ', ' ', ' ', 0, 0, 0, 0, 0, 0, 0, 0, 'O');
INSERT INTO SOC1.PARAV(CODSOC, DATMOD, UTIMOD, CODPAR, CODFCT, LIBPAR, PARA1, PARA2, PARA3, PARM1, PARM2, PARN1, PARN2, PARN3, PARN4, PARN5, PARD1, PARD2, PARD3, ACTIF) VALUES(~societe, to_char(SYSDATE,'YYYYMMDD'), 'OSI_SQL', 'PZNEVE', 'STRPV', ' ', 'TRE', ' ', ' ', ' ', ' ', 0, 0, 0, 0, 0, 0, 0, 0, 'O');
INSERT INTO SOC1.PARAV(CODSOC, DATMOD, UTIMOD, CODPAR, CODFCT, LIBPAR, PARA1, PARA2, PARA3, PARM1, PARM2, PARN1, PARN2, PARN3, PARN4, PARN5, PARD1, PARD2, PARD3, ACTIF) VALUES(~societe, to_char(SYSDATE,'YYYYMMDD'), 'OSI_SQL', 'TARUF', 'STRPV', ' ', 'N', ' ', ' ', ' ', ' ', 0, 0, 0, 0, 0, 0, 0, 0, 'O');
INSERT INTO SOC1.PARAV(CODSOC, DATMOD, UTIMOD, CODPAR, CODFCT, LIBPAR, PARA1, PARA2, PARA3, PARM1, PARM2, PARN1, PARN2, PARN3, PARN4, PARN5, PARD1, PARD2, PARD3, ACTIF) VALUES(~societe, to_char(SYSDATE,'YYYYMMDD'), 'OSI_SQL', 'GENBPL', 'STRPV', ' ', 'S', ' ', ' ', ' ', ' ', 1, 0, 0, 0, 0, 0, 0, 0, 'O');
INSERT INTO SOC1.PARAV(CODSOC, DATMOD, UTIMOD, CODPAR, CODFCT, LIBPAR, PARA1, PARA2, PARA3, PARM1, PARM2, PARN1, PARN2, PARN3, PARN4, PARN5, PARD1, PARD2, PARD3, ACTIF) VALUES(~societe, to_char(SYSDATE,'YYYYMMDD'), 'OSI_SQL', 'PZNEVP', 'STRPV', ' ', 'TRP', ' ', ' ', ' ', ' ', 0, 0, 0, 0, 0, 0, 0, 0, 'O');
INSERT INTO SOC1.PARAV(CODSOC, DATMOD, UTIMOD, CODPAR, CODFCT, LIBPAR, PARA1, PARA2, PARA3, PARM1, PARM2, PARN1, PARN2, PARN3, PARN4, PARN5, PARD1, PARD2, PARD3, ACTIF) VALUES(~societe, to_char(SYSDATE,'YYYYMMDD'), 'OSI_SQL', 'CODASK', 'STRPV', ' ', 'DEPOT', ' ', ' ', ' ', ' ', 0, 0, 0, 0, 0, 0, 0, 0, 'O');
INSERT INTO SOC1.PARAV(CODSOC, DATMOD, UTIMOD, CODPAR, CODFCT, LIBPAR, PARA1, PARA2, PARA3, PARM1, PARM2, PARN1, PARN2, PARN3, PARN4, PARN5, PARD1, PARD2, PARD3, ACTIF) VALUES(~societe, to_char(SYSDATE,'YYYYMMDD'), 'OSI_SQL', 'EDIEVE', 'STRPV', ' ', 'O', ' ', ' ', 'EDT_EXP', ' ', 0, 0, 0, 0, 0, 0, 0, 0, 'O');
INSERT INTO SOC1.PARAV(CODSOC, DATMOD, UTIMOD, CODPAR, CODFCT, LIBPAR, PARA1, PARA2, PARA3, PARM1, PARM2, PARN1, PARN2, PARN3, PARN4, PARN5, PARD1, PARD2, PARD3, ACTIF) VALUES(~societe, to_char(SYSDATE,'YYYYMMDD'), 'OSI_SQL', 'GENBLT', 'STRPV', ' ', 'O', 'O', ' ', ' ', ' ', 0, 0, 0, 0, 0, 0, 0, 0, 'O');
INSERT INTO SOC1.PARAV(CODSOC, DATMOD, UTIMOD, CODPAR, CODFCT, LIBPAR, PARA1, PARA2, PARA3, PARM1, PARM2, PARN1, PARN2, PARN3, PARN4, PARN5, PARD1, PARD2, PARD3, ACTIF) VALUES(~societe, to_char(SYSDATE,'YYYYMMDD'), 'OSI_SQL', 'INVEVE', 'STRPV', ' ', ' ', ' ', ' ', ' ', ' ', 1, 0, 0, 0, 0, 0, 0, 0, 'O');
--
SELECT count(1) FROM SOC1.PARAV WHERE codsoc=~societe and codfct='STRPV';

-- Fin Corps du script
